// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtE6EuaNqYeoJxUBf0jVwe5SuvQsYTBGk',
    appId: '1:981381002012:web:bf213e8e6c89124d6c80d9',
    messagingSenderId: '981381002012',
    projectId: 'flutterinsta-tut',
    authDomain: 'flutterinsta-tut.firebaseapp.com',
    storageBucket: 'flutterinsta-tut.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVywlyCl1uPaWHFz9iX28U24yS72zT9Zw',
    appId: '1:981381002012:android:9965f822cd4832516c80d9',
    messagingSenderId: '981381002012',
    projectId: 'flutterinsta-tut',
    storageBucket: 'flutterinsta-tut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN-f1z0dDsphY5uVlDXaV5kpWcbNLBYKg',
    appId: '1:981381002012:ios:311bd2eecef0f5c16c80d9',
    messagingSenderId: '981381002012',
    projectId: 'flutterinsta-tut',
    storageBucket: 'flutterinsta-tut.appspot.com',
    iosClientId: '981381002012-sd9od7uf1t5fq2rcmseh6pubursc5cfd.apps.googleusercontent.com',
    iosBundleId: 'com.sangwook.instagramflutter',
  );
}
